### ISSUE TITLE
Feedback and bugs

### ISSUE THREAD

**Issue by apollodeathstar** [bellyillish/useful-idiots#6]
- On defensive AI will still try to run off across the map chasing a dog. anti AFK mod used to prevent this.
During combat with mutants like chimeras and pseudogiants they seem to want to run up and point blank shoot them? dunno if this is reg behavior or issues with the defensive setting? Any way to script AI on defensive so they try and keep distance with strong mutants? like they backpedal to maintain distance from the mutant? 

Also noticed this is issue with them vs NPC's where they will try to run in and fight the AI instead of hanging back. Would be better if AI in defensive focused on finding good cover, engaging at distance and other than staying near the player they hung back and did not try to leeroy into the enemies position. maybe on defensive they also use more grenades?

- Prone sometimes causes them to constantly repeat the animation in place

**Comment by apollodeathstar** [comment]
Also I noticed enemies and allies will sometimes start combat with their weapons unloaded? and then they will have to load their weapons before doing anything. can this be changed so outside of combat all their weapons get "reloaded" via script.

**Comment by bellyillish** [comment]
As far as defensive combat goes, something is not working right on your end because they should stay tethered to a point. They shift and find cover periodically but never leave the radius of that point. I don't know if it's a conflict or what, but you're the first person to report this. 

They can't use grenades in scripted combat, only in the "Default" engine combat mode.

Everything else will be addressed in the next update which should drop this week. I mentioned a combat overhaul coming next in the release notes for beta 9, not sure if you saw that. I also talked more about it here: https://discord.com/channels/912320241713958912/1278836517858447471/1309900647088525374.

**Comment by bellyillish** [comment]
And yeah, you read my mind a bit on reloading and the prone animation.

I did figure out a way to make them reload post combat. I also have them reload when losing sight of the enemy during combat right before entering a "search" behavior. I need to do some more investigating because they still seem to reload occasionally when I wouldn't think they'd need to. Sometimes it's because they switch weapons automatically in certain circumstances. But I'm also wondering if they actually switch ammo types as well. Nobody seems to know completely how everything works because a lot of it is in the engine. 

I did find a workaround for the prone animation (the stationary crouch animation also has the same issue but it's more subtle). It's a bit hacky but it seems to work.

This should all be in the next version and I'm super-close to being done.

**Comment by apollodeathstar** [comment]
> And yeah, you read my mind a bit on reloading and the prone animation.
> 
> I did figure out a way to make them reload post combat. I also have them reload when losing sight of the enemy during combat right before entering a "search" behavior. I need to do some more investigating because they still seem to reload occasionally when I wouldn't think they'd need to. Sometimes it's because they switch weapons automatically in certain circumstances. But I'm also wondering if they actually switch ammo types as well. Nobody seems to know completely how everything works because a lot of it is in the engine.
> 
> I did find a workaround for the prone animation (the stationary crouch animation also has the same issue but it's more subtle). It's a bit hacky but it seems to work.
> 
> This should all be in the next version and I'm super-close to being done.

That sounds great! I use ravens close combat so it is very noticable when my enemies and companions switch to their shotgun/sidearm and then have to reload it even though they have never used it that fight. would be great if you can give the option so i can have that enabled for all NPC's as well so every NPC has all their "weapons" reloaded on the map, not just their equipped one. 

Thanks for you hard work
